pragma circom 2.0.6;

include "../circomlib/gates.circom";

template main_template() {
    signal input x1;
    signal input x2;
    signal input x3;
    signal input x4;
    signal input x5;
    signal input x6;
    signal input x7;
    signal input x8;
    signal input x9;
    signal input x10;
    signal input x11;
    signal input x12;
    signal input x13;
    signal input x14;
    signal input x15;
    signal input x16;
    signal input x17;
    signal input x18;
    signal input x19;
    signal input x20;
    component comp_0 = NOT();
    comp_0.in <== x10;
    component comp_1 = NOT();
    comp_1.in <== x16;
    component comp_2 = OR();
    comp_2.a <== comp_0.out;
    comp_2.b <== comp_1.out;
    component comp_3 = OR();
    comp_3.a <== comp_2.out;
    comp_3.b <== x5;
    comp_3.out === 1;
    component comp_4 = NOT();
    comp_4.in <== x6;
    component comp_5 = OR();
    comp_5.a <== x16;
    comp_5.b <== comp_4.out;
    component comp_6 = OR();
    comp_6.a <== comp_5.out;
    comp_6.b <== x5;
    comp_6.out === 1;
    component comp_7 = NOT();
    comp_7.in <== x17;
    component comp_8 = NOT();
    comp_8.in <== x14;
    component comp_9 = OR();
    comp_9.a <== comp_7.out;
    comp_9.b <== comp_8.out;
    component comp_10 = NOT();
    comp_10.in <== x18;
    component comp_11 = OR();
    comp_11.a <== comp_9.out;
    comp_11.b <== comp_10.out;
    comp_11.out === 1;
    component comp_12 = NOT();
    comp_12.in <== x10;
    component comp_13 = NOT();
    comp_13.in <== x15;
    component comp_14 = OR();
    comp_14.a <== comp_12.out;
    comp_14.b <== comp_13.out;
    component comp_15 = OR();
    comp_15.a <== comp_14.out;
    comp_15.b <== x19;
    comp_15.out === 1;
    component comp_16 = NOT();
    comp_16.in <== x1;
    component comp_17 = NOT();
    comp_17.in <== x9;
    component comp_18 = OR();
    comp_18.a <== comp_16.out;
    comp_18.b <== comp_17.out;
    component comp_19 = NOT();
    comp_19.in <== x18;
    component comp_20 = OR();
    comp_20.a <== comp_18.out;
    comp_20.b <== comp_19.out;
    comp_20.out === 1;
    component comp_21 = OR();
    comp_21.a <== x3;
    comp_21.b <== x7;
    component comp_22 = NOT();
    comp_22.in <== x6;
    component comp_23 = OR();
    comp_23.a <== comp_21.out;
    comp_23.b <== comp_22.out;
    comp_23.out === 1;
    component comp_24 = NOT();
    comp_24.in <== x13;
    component comp_25 = OR();
    comp_25.a <== comp_24.out;
    comp_25.b <== x1;
    component comp_26 = OR();
    comp_26.a <== comp_25.out;
    comp_26.b <== x6;
    comp_26.out === 1;
    component comp_27 = NOT();
    comp_27.in <== x2;
    component comp_28 = NOT();
    comp_28.in <== x16;
    component comp_29 = OR();
    comp_29.a <== comp_27.out;
    comp_29.b <== comp_28.out;
    component comp_30 = NOT();
    comp_30.in <== x20;
    component comp_31 = OR();
    comp_31.a <== comp_29.out;
    comp_31.b <== comp_30.out;
    comp_31.out === 1;
    component comp_32 = OR();
    comp_32.a <== x7;
    comp_32.b <== x8;
    component comp_33 = OR();
    comp_33.a <== comp_32.out;
    comp_33.b <== x18;
    comp_33.out === 1;
    component comp_34 = NOT();
    comp_34.in <== x7;
    component comp_35 = OR();
    comp_35.a <== comp_34.out;
    comp_35.b <== x10;
    component comp_36 = NOT();
    comp_36.in <== x20;
    component comp_37 = OR();
    comp_37.a <== comp_35.out;
    comp_37.b <== comp_36.out;
    comp_37.out === 1;
    component comp_38 = NOT();
    comp_38.in <== x14;
    component comp_39 = OR();
    comp_39.a <== x2;
    comp_39.b <== comp_38.out;
    component comp_40 = NOT();
    comp_40.in <== x17;
    component comp_41 = OR();
    comp_41.a <== comp_39.out;
    comp_41.b <== comp_40.out;
    comp_41.out === 1;
    component comp_42 = OR();
    comp_42.a <== x2;
    comp_42.b <== x1;
    component comp_43 = OR();
    comp_43.a <== comp_42.out;
    comp_43.b <== x19;
    comp_43.out === 1;
    component comp_44 = NOT();
    comp_44.in <== x20;
    component comp_45 = OR();
    comp_45.a <== x7;
    comp_45.b <== comp_44.out;
    component comp_46 = NOT();
    comp_46.in <== x1;
    component comp_47 = OR();
    comp_47.a <== comp_45.out;
    comp_47.b <== comp_46.out;
    comp_47.out === 1;
    component comp_48 = NOT();
    comp_48.in <== x11;
    component comp_49 = OR();
    comp_49.a <== comp_48.out;
    comp_49.b <== x1;
    component comp_50 = NOT();
    comp_50.in <== x17;
    component comp_51 = OR();
    comp_51.a <== comp_49.out;
    comp_51.b <== comp_50.out;
    comp_51.out === 1;
    component comp_52 = NOT();
    comp_52.in <== x12;
    component comp_53 = OR();
    comp_53.a <== x3;
    comp_53.b <== comp_52.out;
    component comp_54 = OR();
    comp_54.a <== comp_53.out;
    comp_54.b <== x19;
    comp_54.out === 1;
    0 === 1;
}

component main = main_template();
